services:
  f1-web-helper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f1-web-helper
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
