import { Driver } from "./types";

export const mockDrivers: Driver[] = [
    {
        id: "1",
        position: 1,
        name: "Max Verstappen",
        team: "Red Bull Racing",
        points: 575,
        wins: 19,
        podiums: 21,
        flag: "🇳🇱",
        nationality: "Dutch",
        dateOfBirth: "1997-09-30",
        number: 1,
    },
    {
        id: "2",
        position: 2,
        name: "Sergio Pérez",
        team: "Red Bull Racing",
        points: 285,
        wins: 2,
        podiums: 9,
        flag: "🇲🇽",
        nationality: "Mexican",
        dateOfBirth: "1990-01-26",
        number: 11,
    },
    {
        id: "3",
        position: 3,
        name: "Lewis Hamilton",
        team: "Mercedes",
        points: 234,
        wins: 0,
        podiums: 6,
        flag: "🇬🇧",
        nationality: "British",
        dateOfBirth: "1985-01-07",
        number: 44,
    },
    {
        id: "4",
        position: 4,
        name: "Fernando Alonso",
        team: "Aston Martin",
        points: 206,
        wins: 0,
        podiums: 8,
        flag: "🇪🇸",
        nationality: "Spanish",
        dateOfBirth: "1981-07-29",
        number: 14,
    },
    {
        id: "5",
        position: 5,
        name: "Charles Leclerc",
        team: "Ferrari",
        points: 206,
        wins: 0,
        podiums: 5,
        flag: "🇲🇨",
        nationality: "Monegasque",
        dateOfBirth: "1997-10-16",
        number: 16,
    },
];
